Revert "Bump timeago dep"
This reverts commit 25d1ecc67def24a583161b7d34d8d620e53bbfa4.

Apparently this change caused "TypeError: $.extend is not a function",
so revert for now.